development:
  database: db/xapian_db/development
  adapter:  active_record
  language: es
  writer:   direct

test:
  database: db/xapian_db/test
  adapter:  active_record
  language: es
  writer:   direct

production:
  database: db/xapian_db/production
  adapter:  active_record
  language: es
  writer:   direct
