development:
  database: db/xapian_db/development
  writer:       resque
  resque_queue: xapian_db_development
  language: es

test:
  database: db/xapian_db/test
  adapter:  active_record
  language: es
  writer:   direct

production:
  database: db/xapian_db/production
  writer:       resque
  resque_queue: xapian_db_production
  language: es
